version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb-server
    restart: always
    env_file:
      - .env
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - mariadb-data:/var/lib/mysql
    networks:
      - tp-docker
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask-app:
    image: loicraoult/docker-tp-back
    container_name: flask-app
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - tp-docker

  vuejs-app:
    image: loicraoult/docker-tp-front
    container_name: vuejs-app
    restart: always
    ports:
      - "8080:80"
    networks:
      - tp-docker

volumes:
  mariadb-data:

networks:
  tp-docker:
    driver: bridge
